<? 
// This file is autogenerated. Any changes will be overwritten.

// HELPERS_PATH
include_once HELPERS_PATH . 'account.php';
include_once HELPERS_PATH . 'apk.php';
include_once HELPERS_PATH . 'db.php';
include_once HELPERS_PATH . 'image.php';
include_once HELPERS_PATH . 'mydata.php';
include_once HELPERS_PATH . 'obfuscator.php';
include_once HELPERS_PATH . 'session.php';
include_once HELPERS_PATH . 'strings.php';
include_once HELPERS_PATH . 'view.php';

// MODELS_PATH
include_once MODELS_PATH . '-abstract.php';
include_once MODELS_PATH . '-abstract_logger.php';
include_once MODELS_PATH . 'admin.php';
include_once MODELS_PATH . 'buy_series.php';
include_once MODELS_PATH . 'company.php';
include_once MODELS_PATH . 'company_customer.php';
include_once MODELS_PATH . 'customer.php';
include_once MODELS_PATH . 'day_end.php';
include_once MODELS_PATH . 'department.php';
include_once MODELS_PATH . 'error_logger.php';
include_once MODELS_PATH . 'notification.php';
include_once MODELS_PATH . 'order.php';
include_once MODELS_PATH . 'order_product.php';
include_once MODELS_PATH . 'payment.php';
include_once MODELS_PATH . 'payment_everypay.php';
include_once MODELS_PATH . 'payment_viva.php';
include_once MODELS_PATH . 'product.php';
include_once MODELS_PATH . 'product_category.php';
include_once MODELS_PATH . 'response.php';
include_once MODELS_PATH . 'room.php';
include_once MODELS_PATH . 'sale_document.php';
include_once MODELS_PATH . 'sale_document_product.php';
include_once MODELS_PATH . 'sale_series.php';
include_once MODELS_PATH . 'spec.php';
include_once MODELS_PATH . 'table.php';
include_once MODELS_PATH . 'tip.php';
include_once MODELS_PATH . 'unit.php';
include_once MODELS_PATH . 'user.php';
include_once MODELS_PATH . 'vat_category.php';

// CONTROLLERS_PATH
include_once CONTROLLERS_PATH . 'api.php';
include_once CONTROLLERS_PATH . 'route.php';

// VIEWS_PATH
include_once VIEWS_PATH . 'view_datatable.php';
include_once VIEWS_PATH . 'view_edit.php';



define('APP_MODELS', ['-abstract', '-abstract_logger', 'admin', 'buy_series', 'company', 'company_customer', 'customer', 'day_end', 'department', 'error_logger', 'notification', 'order', 'order_product', 'payment', 'payment_everypay', 'payment_viva', 'product', 'product_category', 'response', 'room', 'sale_document', 'sale_document_product', 'sale_series', 'spec', 'table', 'tip', 'unit', 'user', 'vat_category']);
